version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites
      - ./domains:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    restart: always